@startuml actores
left to right direction
actor Player
usecase Start
usecase Movement
usecase Undo
usecase Redo
usecase Exit
usecase Save
usecase Resume

Player --> Start
Player --> Movement
Player --> Undo
Player --> Redo
Player --> Exit
Player --> Save
Player --> Resume
@enduml

@startuml contexto
state State0 as " "
state State1 as " "
state State2 as " "
state State3 as " "
state State4 as " "

[*] --> State0
State0 --> State1 : Start
State1 --> State1 : Movement
State1 --> State1 : [undoable]Undo
State1 --> State1 : [redoable]Redo
State1 --> State3 : Exit
State3 --> State4 : Save
State1 --> State3 : [isTicTacToe]
State0 --> State4 : [isTicTacToe]
State2 --> State0 : [isResumed]
State4 --> State2 : Resume
State2 --> [*] : [else]
@enduml